BackProp: source/BackProp.cpp source/Network.cpp source/Neuron.cpp source/Input.cpp source/Arguments.cpp
	g++ -o BackProp source/BackProp.cpp source/Network.cpp source/Neuron.cpp source/Input.cpp source/Arguments.cpp
